/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'marialaura' at '9/19/17 10:46 AM' with Gradle 2.14.1
 *
 * @author marialaura, @date 9/19/17 10:46 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
